Section "InputClass"
	Identifier "libinput touchpad catchall"
	Driver "libinput"
	MatchIsTouchpad "on"

	Option "Tapping" "on"
	Option "ClickMethod" "clickfinger"
	Option "NaturalScrolling" "true"
EndSection

Section "InputClass"
	Identifier "libinput keyboard catchall"
	MatchIsKeyboard "on"
	Option "XkbLayout" "real-prog-dvorak,us"
	Option "XkbOptions" "grp:alt_space_toggle"

	Option "AutoRepeat" "250 25"
EndSection
