#!/bin/sh

set -e

files=(
    configs/20-intel.conf               /etc/X11/xorg.conf.d
    configs/30-libinput-overrides.conf  /etc/X11/xorg.conf.d
    configs/99-battery.rules            /etc/udev/rules.d
    configs/real-prog-dvorak            /usr/share/X11/xkb/symbols
    .tmux.conf                          ~
    .vimrc                              ~
    alacritty                           ~/.config
    dunst                               ~/.config
    lf                                  ~/.config
    picom.conf                          ~/.config
    rofi                                ~/.config
)

ask=true
if [[ $# -ge 1 ]] && [[ "$1" =~ -(y|yes) ]]; then
    ask=false
fi

# https://stackoverflow.com/a/5947802
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

dir=$(dirname $(realpath $0))

for ((i=0; i + 1 < ${#files[@]}; i += 2)); do
    file="${files[$i]}"
    dest="${files[$i + 1]}"

    file_basename=$(basename "$file")
    echo -ne "${GREEN}*${NC} symlink ${file_basename} to ${dest}"
    if [[ $ask == "true" ]]; then
        echo -n " (y): "
        read -n 1 input
        echo
        [[ ! "$input" == "y" ]] && continue
    else
        echo
    fi

    dest_file="${dest}/${file_basename}"
    if [[ -L "${dest_file}" ]]; then
        echo -e "${YELLOW}*${NC} symlink ${dest_file} exists"
        continue
    elif [[ -f "${dest_file}" ]]; then
        echo -e "${RED}*${NC} regular file ${dest_file} exists"
        continue
    fi

    ln -s "${dir}/${file}" "${dest_file}" \
        || doas ln -s "${dir}/${file}" "${dest_file}"
done

if [[ $i -ne ${#files[@]} ]]; then
    echo -e "${RED}*${NC} missing destination for ${files[$i]}"
    exit 1
fi
