#!/bin/sh
set -e

files=(
    .vimrc                              ~
    .xinitrc                            ~
    .zshrc                              ~
    alacritty                           ~/.config
    configs/20-intel.conf               /etc/X11/xorg.conf.d
    configs/30-libinput-overrides.conf  /etc/X11/xorg.conf.d
    configs/99-arduino.rules            /etc/udev/rules.d
    configs/99-battery.rules            /etc/udev/rules.d
    configs/real-prog-dvorak            /usr/share/X11/xkb/symbols
    dunst                               ~/.config
    lazygit                             ~/.config
    lf                                  ~/.config
    picom.conf                          ~/.config
    rofi                                ~/.config
    tmux/.tmux.conf                     ~
)
dir=$(dirname $(realpath $0))

# https://stackoverflow.com/a/5947802
GREEN='\x1B[0;32m'
RED='\x1B[0;31m'
NC='\x1B[0m'

for (( i = 0 ; i < ${#files[@]} ; i += 2 )); do
    file="${files[$i]}"

    if [[ ! -e "$dir/$file" ]]; then
        echo -e "$RED$dir/$file does not exist$NC"
        continue
    fi

    dest="${files[$i+1]}/$(basename "$file")"
    echo -ne "$file <- $dest "

    if [[ -L "$dest" ]]; then
        echo -e "${GREEN}ok$NC" # probably
    elif [[ -e "$dest" ]]; then
        echo -e "${RED}! file exists$NC"
    else
        ln -s "$dir/$file" "$dest" || doas ln -s "$dir/$file" "$dest"
        echo -e "${GREEN}ok$NC"
    fi
done

if [[ $i -ne ${#files[@]} ]]; then
    echo -e "${RED}*$NC missing destination for ${files[$i]}"
    exit 1
fi
