#!/bin/sh

set -e

files=(
    configs/20-intel.conf               /etc/X11/xorg.conf.d
    configs/30-libinput-overrides.conf  /etc/X11/xorg.conf.d
    configs/99-battery.rules            /etc/udev/rules.d
    configs/99-arduino.rules            /etc/udev/rules.d
    configs/real-prog-dvorak            /usr/share/X11/xkb/symbols
    .tmux.conf                          ~
    .vimrc                              ~
    .zshrc                              ~
    alacritty                           ~/.config
    dunst                               ~/.config
    lf                                  ~/.config
    picom.conf                          ~/.config
    rofi                                ~/.config
)

ask=true
if [[ $# -ge 1 ]] && [[ "$1" =~ -(y|ye|yes) ]]; then
    ask=false
fi

# https://stackoverflow.com/a/5947802
GREEN='\x1B[0;32m'
YELLOW='\x1B[0;33m'
RED='\x1B[0;31m'
NC='\x1B[0m'

dir=$(dirname $(realpath $0))

for ((i=0; i + 1 < ${#files[@]}; i += 2)); do
    file="${files[$i]}"
    if [[ ! -e "$file" ]]; then
        echo -e "$RED$dir/$file does not exist$NC"
        continue
    fi

    dest="${files[$i + 1]}"
    file_basename=$(basename "$file")
    dest_file="$dest/$file_basename"

    if [[ $ask == "true" ]]; then
        echo -ne "$GREEN$dest_file$NC -> $file (y): "
        read -n 1 input
        echo
        [[ ! "$input" == "y" ]] && continue
    else
        echo -e "$GREEN$dest_file$NC -> $file"
    fi

    if [[ -L "$dest_file" ]]; then
        echo -e "$YELLOW*$NC symbolic link exists\n"
        continue
    elif [[ -f "$dest_file" ]]; then
        echo -e "$RED*$NC regular file exists\n"
        continue
    fi

    ln -s "$dir/$file" "$dest_file" \
        || doas ln -s "$dir/$file" "$dest_file"
    echo
done

if [[ $i -ne ${#files[@]} ]]; then
    echo -e "$RED*$NC missing destination for ${files[$i]}"
    exit 1
fi
