Section "Device"
    Identifier "Intel Graphics"

    Driver "modesetting"
    Option "AccelMethod" "glamor"
    Option "DRI" "3"

    # Driver "intel"
    # Option "AccelMethod" "sna" # default
    ## Option "AccelMethod" "uxa" # fallback
    # Option "DRI" "iris"

    Option "TearFree" "true"


EndSection
